In [4]:
import numpy as np

a = np.array(list("aaasddsdsdsds"))
a

array(['a', 'a', 'a', 's', 'd', 'd', 's', 'd', 's', 'd', 's', 'd', 's'],
      dtype='<U1')

In [6]:
unique, counts = np.unique(a, return_counts=True)
counts

array([3, 5, 5])

In [8]:
p = counts/sum(counts)
p

array([0.23076923, 0.38461538, 0.38461538])

In [9]:
np.log2(p)

array([-2.11547722, -1.37851162, -1.37851162])

In [10]:
-sum(p*np.log2(p))

1.5485806065228545

In [11]:
import math
vfunc = np.vectorize(lambda x: math.log(x,2))
-sum(p*vfunc(p))

1.5485806065228545

In [12]:
import scipy.stats
scipy.stats.entropy(p,base=2)

1.5485806065228545

In [13]:
a = np.array(range(10))

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [17]:
np.any(a)
np.any(a > 10)
np.all(a < 10)

True