In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [2]:
x < 3  

array([ True,  True, False, False, False])

In [3]:
x > 3  

array([False, False, False,  True,  True])

In [4]:
x <= 3  

array([ True,  True,  True, False, False])

In [5]:
x >= 3 

array([False, False,  True,  True,  True])

In [6]:
x != 3 

array([ True,  True, False,  True,  True])

In [7]:
x == 3 

array([False, False,  True, False, False])

In [8]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [9]:
rng = np.random.RandomState(1)
x = rng.randint(10, size=(3, 4))
x

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [10]:
x < 6

array([[ True, False, False,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True]])

In [11]:
print(x)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]


### Подсчеты

In [12]:
np.count_nonzero(x < 6)

7

In [13]:
np.nonzero(x < 6)

(array([0, 0, 1, 1, 1, 2, 2]), array([0, 3, 0, 1, 2, 2, 3]))

``True`` - это 1, а ``False`` - это 0:

In [18]:
np.sum(x[x < 6])
# np.sum((x<6)*x)

17

Сколько значений меньше 6 в каждой строке:

In [19]:
np.sum(x < 6, axis=1)

array([2, 3, 2])

In [20]:
np.any(x > 8)

True

In [21]:
np.any(x < 0)

False

In [22]:
np.all(x < 10)

True

In [23]:
np.all(x == 6)

False

In [24]:
np.all(x < 8, axis=1)

array([False,  True, False])

### Булевы функции

In [26]:
np.sum((x > 3) & (x < 7))


4

In [27]:
np.sum(~( (x <= 3) | (x >= 7) ))


4

## Булевы массивы как маски

In [33]:
x

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [29]:
x < 5

array([[False, False, False, False],
       [ True,  True,  True, False],
       [False, False,  True,  True]])

In [30]:
x[x<5]

array([0, 0, 1, 2, 4])

In [34]:
np.mean(x[x<5])

1.4

``and`` and ``or`` работают над объектом в целом, а ``&`` and ``|`` по элементно