In [9]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [12]:
x < 3  

array([ True,  True, False, False, False])

In [13]:
x > 3  

array([False, False, False,  True,  True])

In [14]:
x <= 3  

array([ True,  True,  True, False, False])

In [15]:
x >= 3 

array([False, False,  True,  True,  True])

In [16]:
x != 3 

array([ True,  True, False,  True,  True])

In [17]:
x == 3 

array([False, False,  True, False, False])

In [18]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [61]:
rng = np.random.RandomState(1)
x = rng.randint(10, size=(3, 4))
x

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [20]:
x < 6

array([[ True, False, False,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True]])

In [21]:
print(x)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]


### Подсчеты

In [22]:
np.count_nonzero(x < 6)

7

In [33]:
np.nonzero(x < 6)

(array([0, 0, 1, 1, 1, 2, 2]), array([0, 3, 0, 1, 2, 2, 3]))

In [ ]:
[[0,0],[0,3],[1,0].....
 

``True`` - это 1, а ``False`` - это 0:

In [65]:
np.sum(x[x < 6])
#x = np.arange(4).reshape(2,2)
#x[ np.array([[True,  True], [False, True]]) ]

#np.sum((x<6)*x)
x

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

Сколько значений меньше 6 в каждой строке:

In [68]:
np.sum(x < 6, axis=1)

array([2, 3, 2])

In [69]:
np.any(x > 8)

True

In [70]:
np.any(x < 0)

False

In [71]:
np.all(x < 10)

True

In [73]:
np.all(x == 6)

False

In [74]:
np.all(x < 8, axis=1)

array([False,  True, False])

### Булевы функции

In [75]:
np.sum((x > 3) & (x < 7))


4

In [76]:
np.sum(~( (x <= 3) | (x >= 7) ))


4

## Булевы массивы как маски

In [77]:
x

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [78]:
x < 5

array([[False, False, False, False],
       [ True,  True,  True, False],
       [False, False,  True,  True]])

In [79]:
x[x<5]

array([0, 0, 1, 2, 4])

In [34]:
np.mean(x[x<5])

1.4

``and`` and ``or`` работают над объектом в целом, а ``&`` and ``|`` по элементно