# Сортировка массивов

Сортироска вставками:

In [1]:
import numpy as np

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [2]:
x = np.array([2, 1, 4, 3, 5])
np.argmin(x[1:])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [3]:
def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x

In [4]:
x = np.array([2, 1, 4, 3, 5])
bogosort(x)

array([1, 2, 3, 4, 5])

## Быстрая сортировка ``np.sort`` и ``np.argsort``

In [5]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [6]:
x.sort()
print(x)

[1 2 3 4 5]


``argsort`` возвращает индексы отсортированных элементов:

In [7]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
i

array([1, 0, 3, 2, 4])

In [8]:
x[i]

array([1, 2, 3, 4, 5])

### Сортировка строк и столбцов:

In [9]:
rand = np.random.RandomState(3)
X = rand.randint(0, 10, (4, 6))
print(X)

[[8 9 3 8 8 0]
 [5 3 9 9 5 7]
 [6 0 4 7 8 1]
 [6 2 2 1 3 5]]


In [10]:
np.sort(X, axis=0)

array([[5, 0, 2, 1, 3, 0],
       [6, 2, 3, 7, 5, 1],
       [6, 3, 4, 8, 8, 5],
       [8, 9, 9, 9, 8, 7]])

In [11]:
np.sort(X, axis=1)

array([[0, 3, 8, 8, 8, 9],
       [3, 5, 5, 7, 9, 9],
       [0, 1, 4, 6, 7, 8],
       [1, 2, 2, 3, 5, 6]])

## Частичная сортировка

In [12]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [13]:
np.partition(X, 2, axis=1)

array([[0, 3, 8, 9, 8, 8],
       [3, 5, 5, 9, 9, 7],
       [0, 1, 4, 7, 8, 6],
       [1, 2, 2, 6, 3, 5]])